In [1]:
from IPython.display import HTML 
import saspy
#sas = saspy.SASsession(cfgname='winlocal', encoding='cp1252')
sas = saspy.SASsession(cfgname='winiomj', encoding='cp1252', iomport=8591)
sas

SAS Connection established. Subprocess id is 47480

Access Method         = IOM
SAS Config name       = winiomj
WORK Path             = /sastmp/SAS_work8A120000090F_tom64-3/SAS_workBFCD0000090F_tom64-3/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.2.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252

In [2]:

ll = sas.submit('''
data NyTest ;
Length t1 t2 t3 8. t4 t5 $100. t6 8.;
do i=1 to 40000;
t1=1;
t2=.;
t3=3;
t4='ÆØÅ -678';
t5='ÆØÅ-678';
t6=.;
t7='ÆØÅ- 678 ';
output;
end;
run;
''')

In [3]:
print(ll['LOG'])

5                                                          The SAS System                          08:24 Tuesday, September 11, 2018

31         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
31       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
32
33
34         data NyTest ;
35         Length t1 t2 t3 8. t4 t5 $100. t6 8.;
36         do i=1 to 40000;
37         t1=1;
38         t2=.;
39         t3=3;
40         t4='ÆØÅ -678';
41         t5='ÆØÅ-678';
42         t6=.;
43         t7='ÆØÅ- 678 ';
44         output;
45         end;
46         run;

NOTE: The data set WORK.NYTEST has 40000 observations and 8 variables.
NOTE: DATA statement used (Total process time):
      real time           0.11 seconds
      cpu time            0.00 seconds


47
48
49         ods html5 (id=saspy_internal) close;ods listing;
50

In [4]:
ds = sas.sasdata('NyTest ')

In [5]:
dsh = sas.sasdata('NyTest ', results='html')

In [6]:
ds.head(30)

    t1  t2  t3        t4       t5  t6   i        t7
0    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   1  ÆØÅ- 678
1    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   2  ÆØÅ- 678
2    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   3  ÆØÅ- 678
3    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   4  ÆØÅ- 678
4    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   5  ÆØÅ- 678
5    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   6  ÆØÅ- 678
6    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   7  ÆØÅ- 678
7    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   8  ÆØÅ- 678
8    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN   9  ÆØÅ- 678
9    1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  10  ÆØÅ- 678
10   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  11  ÆØÅ- 678
11   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  12  ÆØÅ- 678
12   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  13  ÆØÅ- 678
13   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  14  ÆØÅ- 678
14   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  15  ÆØÅ- 678
15   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  16  ÆØÅ- 678
16   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  17  ÆØÅ- 678
17   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  18  ÆØÅ- 678
18   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  19  ÆØÅ- 678
19   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  20  ÆØÅ- 678
20   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  21  ÆØÅ- 678
21   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  22  ÆØÅ- 678
22   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  23  ÆØÅ- 678
23   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  24  ÆØÅ- 678
24   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  25  ÆØÅ- 678
25   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  26  ÆØÅ- 678
26   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  27  ÆØÅ- 678
27   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  28  ÆØÅ- 678
28   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  29  ÆØÅ- 678
29   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  30  ÆØÅ- 678

In [7]:
dsh.tail(100)

In [8]:
df = ds.to_df_CSV()

In [9]:
print(sas.saslog())

1                                                          The SAS System                          08:24 Tuesday, September 11, 2018

NOTE: Copyright (c) 2002-2012 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS04.01M4P11092016)
      Licensed to SAS Institute Inc., Site 1.
NOTE: This session is executing on the Linux 2.6.32-573.18.1.el6.x86_64 (LIN X64) platform.



NOTE: Updated analytical products:

      SAS/STAT 14.2
      SAS/ETS 14.2
      SAS/OR 14.2
      SAS/IML 14.2
      SAS/QC 14.2

NOTE: Additional host information:

 Linux LIN X64 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 CentOS release 6.7 (Final)

You are running SAS 9. Some SAS 8 files will be automatically converted
by the V9 engine; others are incompatible.  Please see
http://support.sas.com/rnd/migration/planning/platform/64bit.html

PROC MIGRATE will preserve current SAS file attributes and is
recommended for converting all your SAS libraries from any
SAS 8 release to SAS 9.  For details and examples, please see
http://support.sas.com/rnd/migration/index.html


This message is contained in the SAS news file, and is presented upon
initialization.  Edit the file "news" in the "misc/base" directory to
display site-specific news and information in the program log.
The command line option "-nonews" will prevent this display.




NOTE: SAS Initialization used (Total process time):
      real time           0.04 seconds
      cpu time            0.00 seconds

1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6
2                                                          The SAS System                          08:24 Tuesday, September 11, 2018

7          ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
7        ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
8          ;*';*";*/;
9          libname work list;
NOTE: Libref=   WORK
      Scope=    IOM ROOT COMP ENV
      Engine=   V9
      Access=   TEMP
      Physical Name= /sastmp/SAS_work8A120000090F_tom64-3/SAS_workBFCD0000090F_tom64-3
      Filename= /sastmp/SAS_work8A120000090F_tom64-3/SAS_workBFCD0000090F_tom64-3
      Inode Number= 37143158007
      Access Permission= rwxr-xr-x
      Owner Name= sastpw
      File Size=              0KB
      File Size (bytes)= 162
10
11         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
12
13         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
14
3                                                          The SAS System                          08:24 Tuesday, September 11, 2018

15         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
15       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
16         ;*';*";*/;
17         %put SYSV=&sysvlong4;
SYSV=9.04.01M4P11092016
18
19         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
20
21         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
22
4                                                          The SAS System                          08:24 Tuesday, September 11, 2018

23         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
23       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
24         ;*';*";*/;
25         proc options option=encoding;run;

    SAS (r) Proprietary Software Release 9.04.01M4P11092016

 ENCODING=WLATIN1  Specifies the default character-set encoding for the SAS session.
NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


26
27         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
28
29         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
30
5                                                          The SAS System                          08:24 Tuesday, September 11, 2018

31         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
31       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
32         ;*';*";*/;
33
34         data NyTest ;
35         Length t1 t2 t3 8. t4 t5 $100. t6 8.;
36         do i=1 to 40000;
37         t1=1;
38         t2=.;
39         t3=3;
40         t4='ÆØÅ -678';
41         t5='ÆØÅ-678';
42         t6=.;
43         t7='ÆØÅ- 678 ';
44         output;
45         end;
46         run;

NOTE: The data set WORK.NYTEST has 40000 observations and 8 variables.
NOTE: DATA statement used (Total process time):
      real time           0.11 seconds
      cpu time            0.00 seconds


47
48
49         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
50
51         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
52
6                                                          The SAS System                          08:24 Tuesday, September 11, 2018

53         ;*';*";*/;
54         data _null_; e = exist('user.NyTest ');
55         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


56
57
58         ;*';*";*/;
59         %put E3969440A681A2408885998500000006;
E3969440A681A2408885998500000006
60
7                                                          The SAS System                          08:24 Tuesday, September 11, 2018

61         ;*';*";*/;
62         data _null_; e = exist('WORK.NyTest ');
63         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


64
65
66         ;*';*";*/;
67         %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
68
8                                                          The SAS System                          08:24 Tuesday, September 11, 2018

69         ;*';*";*/;
70         data _null_; e = exist('user.NyTest ');
71         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


72
73
74         ;*';*";*/;
75         %put E3969440A681A2408885998500000008;
E3969440A681A2408885998500000008
76
9                                                          The SAS System                          08:24 Tuesday, September 11, 2018

77         ;*';*";*/;
78         data _null_; e = exist('WORK.NyTest ');
79         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


80
81
82         ;*';*";*/;
83         %put E3969440A681A2408885998500000009;
E3969440A681A2408885998500000009
84
10                                                         The SAS System                          08:24 Tuesday, September 11, 2018

85         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
85       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
86         ;*';*";*/;
87         data _head ; set WORK.NyTest  (obs=30 ); run;

NOTE: There were 30 observations read from the data set WORK.NYTEST.
NOTE: The data set WORK._HEAD has 30 observations and 8 variables.
NOTE: DATA statement used (Total process time):
      real time           0.02 seconds
      cpu time            0.00 seconds


88
89         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
90
91         %put E3969440A681A2408885998500000010;
E3969440A681A2408885998500000010
92
11                                                         The SAS System                          08:24 Tuesday, September 11, 2018

93         ;*';*";*/;
94         proc sql;
94       !           create view sasdata2dataframe as select * from work._head;
NOTE: SQL view WORK.SASDATA2DATAFRAME has been defined.
94       !                                                                     quit;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.01 seconds
      cpu time            0.00 seconds


95         data _null_; file LOG; d = open('sasdata2dataframe');
96         length var $256;
97         lrecl = attrn(d, 'LRECL'); nvars = attrn(d, 'NVARS');
98         lr='LRECL='; vn='VARNUMS='; vl='VARLIST='; vt='VARTYPE='; vf='VARFMT=';
99         put lr lrecl; put vn nvars; put vl;
100        do i = 1 to nvars; var = compress(varname(d, i), '00'x); put var; end;
101        put vt;
102        do i = 1 to nvars; var = vartype(d, i); put var; end;
103        run;

LRECL= 249
VARNUMS= 8
VARLIST=
t1
t2
t3
t4
t5
t6
i
t7
VARTYPE=
N
N
N
C
C
N
N
C
NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds


104
105        ;*';*";*/;
106        %put E3969440A681A2408885998500000012;
E3969440A681A2408885998500000012
107
12                                                         The SAS System                          08:24 Tuesday, September 11, 2018

108        ;*';*";*/;
109        data _null_; set work._head(obs=1 );put 'FMT_CATS=';
110        _tom = vformatn('t1'n);put _tom;
111        _tom = vformatn('t2'n);put _tom;
112        _tom = vformatn('t3'n);put _tom;
113        _tom = vformatn('t4'n);put _tom;
114        _tom = vformatn('t5'n);put _tom;
115        _tom = vformatn('t6'n);put _tom;
116        _tom = vformatn('i'n);put _tom;
117        _tom = vformatn('t7'n);put _tom;
118        run;

FMT_CATS=
BEST
BEST
BEST
$
$
BEST
BEST
$
NOTE: There were 1 observations read from the data set WORK._HEAD.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


119
120        ;*';*";*/;
121        %put E3969440A681A2408885998500000013;
E3969440A681A2408885998500000013
122
15                                                         The SAS System                          08:24 Tuesday, September 11, 2018

130        ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
130      ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
131        ;*';*";*/;
132        proc delete data=work._head; run;

NOTE: Deleting WORK._HEAD (memtype=DATA).
NOTE: PROCEDURE DELETE used (Total process time):
      real time           0.01 seconds
      cpu time            0.00 seconds


133
134        ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
135
136        %put E3969440A681A2408885998500000014;
E3969440A681A2408885998500000014
137
16                                                         The SAS System                          08:24 Tuesday, September 11, 2018

138        ;*';*";*/;
139        data _null_; e = exist('WORK.NyTest ');
140        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


141
142
143        ;*';*";*/;
144        %put E3969440A681A2408885998500000015;
E3969440A681A2408885998500000015
145
17                                                         The SAS System                          08:24 Tuesday, September 11, 2018

146        ;*';*";*/;
147        proc sql;
147      !          select count(*) format best32. into :lastobs from WORK.NyTest ;
147      !                                                                         %put lastobs=&lastobs tom;quit;
lastobs=                           40000 tom
NOTE: The PROCEDURE SQL printed page 1.
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.02 seconds
      cpu time            0.00 seconds


148
149        ;*';*";*/;
150        %put E3969440A681A2408885998500000016;
E3969440A681A2408885998500000016
151
18                                                         The SAS System                          08:24 Tuesday, September 11, 2018

152        ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
152      ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
153        ;*';*";*/;
154        proc print data=WORK.NyTest (obs=40000 firstobs=39901 );run;

NOTE: There were 100 observations read from the data set WORK.NYTEST.
NOTE: PROCEDURE PRINT used (Total process time):
      real time           0.09 seconds
      cpu time            0.09 seconds


155
156        ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
157
158        %put E3969440A681A2408885998500000017;
E3969440A681A2408885998500000017
159
19                                                         The SAS System                          08:24 Tuesday, September 11, 2018

160        ;*';*";*/;
161        data _null_; e = exist('WORK.NyTest ');
162        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


163
164
165        ;*';*";*/;
166        %put E3969440A681A2408885998500000018;
E3969440A681A2408885998500000018
167
20                                                         The SAS System                          08:24 Tuesday, September 11, 2018

168        ;*';*";*/;
169        data _null_; e = exist('WORK.NyTest ');
170        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


171
172
173        ;*';*";*/;
174        %put E3969440A681A2408885998500000019;
E3969440A681A2408885998500000019
175
21                                                         The SAS System                          08:24 Tuesday, September 11, 2018

176        ;*';*";*/;
177        proc sql;
177      !           create view sasdata2dataframe as select * from WORK.NyTest ;
NOTE: SQL view WORK.SASDATA2DATAFRAME has been defined.
177      !                                                                       quit;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.03 seconds
      cpu time            0.00 seconds


178        data _null_; file LOG; d = open('sasdata2dataframe');
179        length var $256;
180        lrecl = attrn(d, 'LRECL'); nvars = attrn(d, 'NVARS');
181        lr='LRECL='; vn='VARNUMS='; vl='VARLIST='; vt='VARTYPE='; vf='VARFMT=';
182        put lr lrecl; put vn nvars; put vl;
183        do i = 1 to nvars; var = compress(varname(d, i), '00'x); put var; end;
184        put vt;
185        do i = 1 to nvars; var = vartype(d, i); put var; end;
186        run;

LRECL= 249
VARNUMS= 8
VARLIST=
t1
t2
t3
t4
t5
t6
i
t7
VARTYPE=
N
N
N
C
C
N
N
C
NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      cpu time            0.00 seconds


187
188        ;*';*";*/;
189        %put E3969440A681A2408885998500000021;
E3969440A681A2408885998500000021
190
22                                                         The SAS System                          08:24 Tuesday, September 11, 2018

191        ;*';*";*/;
192        data _null_; set WORK.NyTest (obs=1 );put 'FMT_CATS=';
193        _tom = vformatn('t1'n);put _tom;
194        _tom = vformatn('t2'n);put _tom;
195        _tom = vformatn('t3'n);put _tom;
196        _tom = vformatn('t4'n);put _tom;
197        _tom = vformatn('t5'n);put _tom;
198        _tom = vformatn('t6'n);put _tom;
199        _tom = vformatn('i'n);put _tom;
200        _tom = vformatn('t7'n);put _tom;
201        run;

FMT_CATS=
BEST
BEST
BEST
$
$
BEST
BEST
$
NOTE: There were 1 observations read from the data set WORK.NYTEST.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


202
203        ;*';*";*/;
204        %put E3969440A681A2408885998500000022;
E3969440A681A2408885998500000022
205
23                                                         The SAS System                          08:24 Tuesday, September 11, 2018

206        ;*';*";*/;
207        data sasdata2dataframe / view=sasdata2dataframe; set WORK.NyTest ;
208        format 't1'n best32. 't2'n best32. 't3'n best32. 't6'n best32. 'i'n best32. ;
209         run;

NOTE: DATA STEP view saved on file WORK.SASDATA2DATAFRAME.
NOTE: A stored DATA STEP view cannot run under a different operating system.
NOTE: DATA statement used (Total process time):
      real time           0.06 seconds
      cpu time            0.01 seconds


210
211
212        ;*';*";*/;
213        %put E3969440A681A2408885998500000023;
E3969440A681A2408885998500000023
214
24                                                         The SAS System                          08:24 Tuesday, September 11, 2018

215        proc export data=sasdata2dataframe outfile=_tomods1 dbms=csv replace;
215      !                                                                       run
216        ;

NOTE: View WORK.SASDATA2DATAFRAME.VIEW used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

NOTE: View WORK.SASDATA2DATAFRAME.VIEW used (Total process time):
      real time           0.03 seconds
      cpu time            0.00 seconds

NOTE: There were 263 observations read from the data set WORK.NYTEST.
217         /**********************************************************************
218         *   PRODUCT:   SAS
219         *   VERSION:   9.4
220         *   CREATOR:   External File Interface
221         *   DATE:      11SEP18
222         *   DESC:      Generated SAS Datastep Code
223         *   TEMPLATE SOURCE:  (None Specified.)
224         ***********************************************************************/
225            data _null_;
226            %let _EFIERR_ = 0; /* set the ERROR detection macro variable */
227            %let _EFIREC_ = 0;     /* clear export record count macro variable */
228            file _TOMODS1 delimiter=',' DSD DROPOVER ;
229            if _n_ = 1 then        /* write column names or labels */
230             do;
231               put
232                  "t1"
233               ','
234                  "t2"
235               ','
236                  "t3"
237               ','
238                  "t4"
239               ','
240                  "t5"
241               ','
242                  "t6"
243               ','
244                  "i"
245               ','
246                  "t7"
247               ;
248             end;
249           set  SASDATA2DATAFRAME   end=EFIEOD;
250               format t1 best32. ;
251               format t2 best32. ;
252               format t3 best32. ;
253               format t4 $100. ;
254               format t5 $100. ;
255               format t6 best32. ;
256               format i best32. ;
257               format t7 $9. ;
258             do;
259               EFIOUT + 1;
260               put t1 @;
261               put t2 @;
262               put t3 @;
263               put t4 $ @;
264               put t5 $ @;
265               put t6 @;
266               put i @;
267               put t7 $ ;
268               ;
269             end;
270            if _ERROR_ then call symputx('_EFIERR_',1);  /* set ERROR detection macro variable */
271            if EFIEOD then call symputx('_EFIREC_',EFIOUT);
272            run;


In [10]:
df.head(30)

     t1  t2   t3        t4       t5  t6     i        t7
0   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   1.0  ÆØÅ- 678
1   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   2.0  ÆØÅ- 678
2   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   3.0  ÆØÅ- 678
3   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   4.0  ÆØÅ- 678
4   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   5.0  ÆØÅ- 678
5   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   6.0  ÆØÅ- 678
6   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   7.0  ÆØÅ- 678
7   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   8.0  ÆØÅ- 678
8   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN   9.0  ÆØÅ- 678
9   1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  10.0  ÆØÅ- 678
10  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  11.0  ÆØÅ- 678
11  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  12.0  ÆØÅ- 678
12  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  13.0  ÆØÅ- 678
13  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  14.0  ÆØÅ- 678
14  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  15.0  ÆØÅ- 678
15  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  16.0  ÆØÅ- 678
16  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  17.0  ÆØÅ- 678
17  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  18.0  ÆØÅ- 678
18  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  19.0  ÆØÅ- 678
19  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  20.0  ÆØÅ- 678
20  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  21.0  ÆØÅ- 678
21  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  22.0  ÆØÅ- 678
22  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  23.0  ÆØÅ- 678
23  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  24.0  ÆØÅ- 678
24  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  25.0  ÆØÅ- 678
25  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  26.0  ÆØÅ- 678
26  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  27.0  ÆØÅ- 678
27  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  28.0  ÆØÅ- 678
28  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  29.0  ÆØÅ- 678
29  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  30.0  ÆØÅ- 678

In [11]:
df

        t1  t2   t3        t4       t5  t6        i        t7
0      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      1.0  ÆØÅ- 678
1      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      2.0  ÆØÅ- 678
2      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      3.0  ÆØÅ- 678
3      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      4.0  ÆØÅ- 678
4      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      5.0  ÆØÅ- 678
5      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      6.0  ÆØÅ- 678
6      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      7.0  ÆØÅ- 678
7      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      8.0  ÆØÅ- 678
8      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN      9.0  ÆØÅ- 678
9      1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     10.0  ÆØÅ- 678
10     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     11.0  ÆØÅ- 678
11     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     12.0  ÆØÅ- 678
12     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     13.0  ÆØÅ- 678
13     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     14.0  ÆØÅ- 678
14     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     15.0  ÆØÅ- 678
15     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     16.0  ÆØÅ- 678
16     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     17.0  ÆØÅ- 678
17     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     18.0  ÆØÅ- 678
18     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     19.0  ÆØÅ- 678
19     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     20.0  ÆØÅ- 678
20     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     21.0  ÆØÅ- 678
21     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     22.0  ÆØÅ- 678
22     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     23.0  ÆØÅ- 678
23     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     24.0  ÆØÅ- 678
24     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     25.0  ÆØÅ- 678
25     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     26.0  ÆØÅ- 678
26     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     27.0  ÆØÅ- 678
27     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     28.0  ÆØÅ- 678
28     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     29.0  ÆØÅ- 678
29     1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN     30.0  ÆØÅ- 678
...    ...  ..  ...       ...      ...  ..      ...       ...
39970  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39971.0  ÆØÅ- 678
39971  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39972.0  ÆØÅ- 678
39972  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39973.0  ÆØÅ- 678
39973  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39974.0  ÆØÅ- 678
39974  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39975.0  ÆØÅ- 678
39975  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39976.0  ÆØÅ- 678
39976  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39977.0  ÆØÅ- 678
39977  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39978.0  ÆØÅ- 678
39978  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39979.0  ÆØÅ- 678
39979  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39980.0  ÆØÅ- 678
39980  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39981.0  ÆØÅ- 678
39981  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39982.0  ÆØÅ- 678
39982  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39983.0  ÆØÅ- 678
39983  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39984.0  ÆØÅ- 678
39984  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39985.0  ÆØÅ- 678
39985  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39986.0  ÆØÅ- 678
39986  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39987.0  ÆØÅ- 678
39987  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39988.0  ÆØÅ- 678
39988  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39989.0  ÆØÅ- 678
39989  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39990.0  ÆØÅ- 678
39990  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39991.0  ÆØÅ- 678
39991  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39992.0  ÆØÅ- 678
39992  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39993.0  ÆØÅ- 678
39993  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39994.0  ÆØÅ- 678
39994  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39995.0  ÆØÅ- 678
39995  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39996.0  ÆØÅ- 678
39996  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39997.0  ÆØÅ- 678
39997  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39998.0  ÆØÅ- 678
39998  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  39999.0  ÆØÅ- 678
39999  1.0 NaN  3.0  ÆØÅ -678  ÆØÅ-678 NaN  40000.0  ÆØÅ- 678

[40000 rows x 8 columns]

In [12]:
df2 = ds.to_df()

In [13]:
df2

       t1  t2  t3        t4       t5  t6      i        t7
0       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      1  ÆØÅ- 678
1       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      2  ÆØÅ- 678
2       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      3  ÆØÅ- 678
3       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      4  ÆØÅ- 678
4       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      5  ÆØÅ- 678
5       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      6  ÆØÅ- 678
6       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      7  ÆØÅ- 678
7       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      8  ÆØÅ- 678
8       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN      9  ÆØÅ- 678
9       1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     10  ÆØÅ- 678
10      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     11  ÆØÅ- 678
11      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     12  ÆØÅ- 678
12      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     13  ÆØÅ- 678
13      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     14  ÆØÅ- 678
14      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     15  ÆØÅ- 678
15      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     16  ÆØÅ- 678
16      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     17  ÆØÅ- 678
17      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     18  ÆØÅ- 678
18      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     19  ÆØÅ- 678
19      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     20  ÆØÅ- 678
20      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     21  ÆØÅ- 678
21      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     22  ÆØÅ- 678
22      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     23  ÆØÅ- 678
23      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     24  ÆØÅ- 678
24      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     25  ÆØÅ- 678
25      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     26  ÆØÅ- 678
26      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     27  ÆØÅ- 678
27      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     28  ÆØÅ- 678
28      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     29  ÆØÅ- 678
29      1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN     30  ÆØÅ- 678
...    ..  ..  ..       ...      ...  ..    ...       ...
39970   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39971  ÆØÅ- 678
39971   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39972  ÆØÅ- 678
39972   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39973  ÆØÅ- 678
39973   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39974  ÆØÅ- 678
39974   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39975  ÆØÅ- 678
39975   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39976  ÆØÅ- 678
39976   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39977  ÆØÅ- 678
39977   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39978  ÆØÅ- 678
39978   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39979  ÆØÅ- 678
39979   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39980  ÆØÅ- 678
39980   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39981  ÆØÅ- 678
39981   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39982  ÆØÅ- 678
39982   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39983  ÆØÅ- 678
39983   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39984  ÆØÅ- 678
39984   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39985  ÆØÅ- 678
39985   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39986  ÆØÅ- 678
39986   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39987  ÆØÅ- 678
39987   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39988  ÆØÅ- 678
39988   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39989  ÆØÅ- 678
39989   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39990  ÆØÅ- 678
39990   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39991  ÆØÅ- 678
39991   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39992  ÆØÅ- 678
39992   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39993  ÆØÅ- 678
39993   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39994  ÆØÅ- 678
39994   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39995  ÆØÅ- 678
39995   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39996  ÆØÅ- 678
39996   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39997  ÆØÅ- 678
39997   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39998  ÆØÅ- 678
39998   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  39999  ÆØÅ- 678
39999   1 NaN   3  ÆØÅ -678  ÆØÅ-678 NaN  40000  ÆØÅ- 678

[40000 rows x 8 columns]

In [14]:
sas

Access Method         = IOM
SAS Config name       = winiomj
WORK Path             = /sastmp/SAS_work8A120000090F_tom64-3/SAS_workBFCD0000090F_tom64-3/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.2.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252