In [1]:
import pandas as pd
data_url = "https://forge.scilab.org/index.php/p/rdataset/source/file/master/csv/datasets/cars.csv"
df_python = pd.read_csv(data_url)
df_python.drop(df_python.columns[[0]], axis=1, inplace=True)

In [2]:
df_python

    speed  dist
0       4     2
1       4    10
2       7     4
3       7    22
4       8    16
5       9    10
6      10    18
7      10    26
8      10    34
9      11    17
10     11    28
11     12    14
12     12    20
13     12    24
14     12    28
15     13    26
16     13    34
17     13    34
18     13    46
19     14    26
20     14    36
21     14    60
22     14    80
23     15    20
24     15    26
25     15    54
26     16    32
27     16    40
28     17    32
29     17    40
30     17    50
31     18    42
32     18    56
33     18    76
34     18    84
35     19    36
36     19    46
37     19    68
38     20    32
39     20    48
40     20    52
41     20    56
42     20    64
43     22    66
44     23    54
45     24    70
46     24    92
47     24    93
48     24   120
49     25    85

In [3]:
import saspy
session_sas = saspy.SASsession(cfgname='winlocal')
session_sas

SAS Connection established. Subprocess id is 25500

Access Method         = IOM
SAS Config name       = winlocal
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD532_d10a626_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 2.2.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252

In [4]:
df_sas = session_sas.df2sd(df_python)

In [5]:
print(session_sas.saslog())

1                                                          The SAS System                        09:08 Wednesday, September 12, 2018

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M5)
      Licensed to Microsoft Windows for x64 All Compatible Non-Plann, Site 70068130.
NOTE: This session is executing on the X64_10PRO  platform.



NOTE: Updated analytical products:

      SAS/STAT 14.3
      SAS/ETS 14.3
      SAS/OR 14.3
      SAS/QC 14.3

NOTE: Additional host information:

 X64_10PRO WIN 10.0.16299  Workstation

NOTE: SAS Initialization used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6
2                                                          The SAS System                        09:08 Wednesday, September 12, 2018

7          ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
7        ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
8          ;*';*";*/;
9          libname work list;
NOTE: Libref=   WORK
      Scope=    IOM ROOT COMP ENV
      Engine=   V9
      Access=   TEMP
      Physical Name= C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD532_d10a626_\Prc2
      Filename= C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD532_d10a626_\Prc2
      Owner Name= CARYNT\sastpw
      File Size=              4KB
      File Size (bytes)= 4096
10
11         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
12
13         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
14
3                                                          The SAS System                        09:08 Wednesday, September 12, 2018

15         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
15       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
16         ;*';*";*/;
17         %put SYSV=&sysvlong4;
SYSV=9.04.01M5P09132017
18
19         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
20
21         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
22
4                                                          The SAS System                        09:08 Wednesday, September 12, 2018

23         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
23       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
24         ;*';*";*/;
25         proc options option=encoding;run;

    SAS (r) Proprietary Software Release 9.4  TS1M5

 ENCODING=WLATIN1  Specifies the default character-set encoding for the SAS session.
NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


26
27         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
28
29         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
30
5                                                          The SAS System                        09:08 Wednesday, September 12, 2018

31         data _df;
32         length  'speed'n 8 'dist'n 8;
33         infile datalines delimiter='03'x DSD STOPOVER;
34         input @;
35         if _infile_ = '' then delete;
36         input 'speed'n 'dist'n ;
37         datalines4;

6                                                          The SAS System                        09:08 Wednesday, September 12, 2018

NOTE: DATA statement used (Total process time):
      real time           0.02 seconds
      cpu time            0.01 seconds

NOTE: The data set WORK._DF has 50 observations and 2 variables.

89         ;;;;
90         run;
91
7                                                          The SAS System                        09:08 Wednesday, September 12, 2018

92         ;*';*";*/;
93
94
95         ;*';*";*/;
96         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
97
8                                                          The SAS System                        09:08 Wednesday, September 12, 2018

98         ;*';*";*/;
99         data _null_; e = exist('_df');
100        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.02 seconds
      cpu time            0.00 seconds


101
102
103        ;*';*";*/;
104        %put E3969440A681A2408885998500000006;
E3969440A681A2408885998500000006
105
9                                                          The SAS System                        09:08 Wednesday, September 12, 2018

106        ;*';*";*/;
107        data _null_; e = exist('user._df');
108        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds


109
110
111        ;*';*";*/;
112        %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
113

In [6]:
df_sas.describe()

  Variable   N  NMiss  Median   Mean     StdDev  Min  P25  P50  P75  Max
0    speed  50      0      15  15.40   5.287644    4   12   15   19   25
1     dist  50      0      36  42.98  25.769377    2   26   36   56  120

In [7]:
print(session_sas.saslog())

1                                                          The SAS System                        09:08 Wednesday, September 12, 2018

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M5)
      Licensed to Microsoft Windows for x64 All Compatible Non-Plann, Site 70068130.
NOTE: This session is executing on the X64_10PRO  platform.



NOTE: Updated analytical products:

      SAS/STAT 14.3
      SAS/ETS 14.3
      SAS/OR 14.3
      SAS/QC 14.3

NOTE: Additional host information:

 X64_10PRO WIN 10.0.16299  Workstation

NOTE: SAS Initialization used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6
2                                                          The SAS System                        09:08 Wednesday, September 12, 2018

7          ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
7        ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
8          ;*';*";*/;
9          libname work list;
NOTE: Libref=   WORK
      Scope=    IOM ROOT COMP ENV
      Engine=   V9
      Access=   TEMP
      Physical Name= C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD532_d10a626_\Prc2
      Filename= C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD532_d10a626_\Prc2
      Owner Name= CARYNT\sastpw
      File Size=              4KB
      File Size (bytes)= 4096
10
11         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
12
13         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
14
3                                                          The SAS System                        09:08 Wednesday, September 12, 2018

15         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
15       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
16         ;*';*";*/;
17         %put SYSV=&sysvlong4;
SYSV=9.04.01M5P09132017
18
19         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
20
21         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
22
4                                                          The SAS System                        09:08 Wednesday, September 12, 2018

23         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
23       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
24         ;*';*";*/;
25         proc options option=encoding;run;

    SAS (r) Proprietary Software Release 9.4  TS1M5

 ENCODING=WLATIN1  Specifies the default character-set encoding for the SAS session.
NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


26
27         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
28
29         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
30
5                                                          The SAS System                        09:08 Wednesday, September 12, 2018

31         data _df;
32         length  'speed'n 8 'dist'n 8;
33         infile datalines delimiter='03'x DSD STOPOVER;
34         input @;
35         if _infile_ = '' then delete;
36         input 'speed'n 'dist'n ;
37         datalines4;

6                                                          The SAS System                        09:08 Wednesday, September 12, 2018

NOTE: DATA statement used (Total process time):
      real time           0.02 seconds
      cpu time            0.01 seconds

NOTE: The data set WORK._DF has 50 observations and 2 variables.

89         ;;;;
90         run;
91
7                                                          The SAS System                        09:08 Wednesday, September 12, 2018

92         ;*';*";*/;
93
94
95         ;*';*";*/;
96         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
97
8                                                          The SAS System                        09:08 Wednesday, September 12, 2018

98         ;*';*";*/;
99         data _null_; e = exist('_df');
100        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.02 seconds
      cpu time            0.00 seconds


101
102
103        ;*';*";*/;
104        %put E3969440A681A2408885998500000006;
E3969440A681A2408885998500000006
105
9                                                          The SAS System                        09:08 Wednesday, September 12, 2018

106        ;*';*";*/;
107        data _null_; e = exist('user._df');
108        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds


109
110
111        ;*';*";*/;
112        %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
113
10                                                         The SAS System                        09:08 Wednesday, September 12, 2018

114        ;*';*";*/;
115        data _null_; e = exist('WORK._df');
116        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds


117
118
119        ;*';*";*/;
120        %put E3969440A681A2408885998500000008;
E3969440A681A2408885998500000008
121
11                                                         The SAS System                        09:08 Wednesday, September 12, 2018

122        ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
122      ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
123        ;*';*";*/;
124        proc means data=WORK._df  stackodsoutput n nmiss median mean std min p25 p50 p75 max; ods output Summary=work._summary;
124      ! run;
NOTE: The data set WORK._SUMMARY has 2 observations and 11 variables.
NOTE: There were 50 observations read from the data set WORK._DF.
NOTE: PROCEDURE MEANS used (Total process time):
      real time           0.08 seconds
      cpu time            0.04 seconds


125
126        ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
127
128        %put E3969440A681A2408885998500000009;
E3969440A681A2408885998500000009
129
12                                                         The SAS System                        09:08 Wednesday, September 12, 2018

130        ;*';*";*/;
131        proc sql;
131      !           create view sasdata2dataframe as select * from work._summary;
NOTE: SQL view WORK.SASDATA2DATAFRAME has been defined.
131      !                                                                        quit;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.08 seconds
      cpu time            0.00 seconds


132        data _null_; file LOG; d = open('sasdata2dataframe');
133        length var $256;
134        lrecl = attrn(d, 'LRECL'); nvars = attrn(d, 'NVARS');
135        lr='LRECL='; vn='VARNUMS='; vl='VARLIST='; vt='VARTYPE='; vf='VARFMT=';
136        put lr lrecl; put vn nvars; put vl;
137        do i = 1 to nvars; var = compress(varname(d, i), '00'x); put var; end;
138        put vt;
139        do i = 1 to nvars; var = vartype(d, i); put var; end;
140        run;

LRECL= 88
VARNUMS= 11
VARLIST=
Variable
N
NMiss
Median
Mean
StdDev
Min
P25
P50
P75
Max
VARTYPE=
C
N
N
N
N
N
N
N
N
N
N
NOTE: DATA statement used (Total process time):
      real time           0.03 seconds
      cpu time            0.03 seconds


141
142        ;*';*";*/;
143        %put E3969440A681A2408885998500000011;
E3969440A681A2408885998500000011
144
13                                                         The SAS System                        09:08 Wednesday, September 12, 2018

145        ;*';*";*/;
146        data _null_; set work._summary(obs=1 );put 'FMT_CATS=';
147        _tom = vformatn('Variable'n);put _tom;
148        _tom = vformatn('N'n);put _tom;
149        _tom = vformatn('NMiss'n);put _tom;
150        _tom = vformatn('Median'n);put _tom;
151        _tom = vformatn('Mean'n);put _tom;
152        _tom = vformatn('StdDev'n);put _tom;
153        _tom = vformatn('Min'n);put _tom;
154        _tom = vformatn('P25'n);put _tom;
155        _tom = vformatn('P50'n);put _tom;
156        _tom = vformatn('P75'n);put _tom;
157        _tom = vformatn('Max'n);put _tom;
158        run;

FMT_CATS=
$
BEST
BEST
D
D
D
D
D
D
D
D
NOTE: There were 1 observations read from the data set WORK._SUMMARY.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


159
160        ;*';*";*/;
161        %put E3969440A681A2408885998500000012;
E3969440A681A2408885998500000012
162
16                                                         The SAS System                        09:08 Wednesday, September 12, 2018

170        ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
170      ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
171        ;*';*";*/;
172        proc delete data=work._summary; run;

NOTE: Deleting WORK._SUMMARY (memtype=DATA).
NOTE: PROCEDURE DELETE used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


173
174        ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
175
176        %put E3969440A681A2408885998500000013;
E3969440A681A2408885998500000013
177